[package]
name = "upload"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "main.rs"

[dependencies]
candid = "0.9.6"
ic-agent = "0.27.0"
ic-cdk = "0.11.0"
serde_json = "1.0.83"
tokio = { version = "1.32.0", features = ["full"] }
